import Head from "next/head"
import Image from "next/image"
import { promises as fs } from "fs"

import styles from "../styles/Home.module.css"

export default function Home({ entries }: { entries: string[] }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <ul>
            {entries.map((entry, idx) => (
              <li key={idx}>{entry}</li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const readme = await fs.readFile("README.md", "utf8")

  const entries = readme
    .split("\n")
    .filter((line) => line.startsWith("- "))
    .map((l) => l.slice(2))

  return {
    props: {
      entries,
    },
  }
}
